# Creating Arrys

In [1]:
import numpy as np

**1D ARRAY**

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

**2D ARRAY**

In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
b.shape #shape of array

(2, 3)

In [5]:
b.ndim #array dimensions (axes)

2

In [6]:
b.dtype #datatype of array

dtype('int32')

In [7]:
b.size #size (total number of elements) of array

6

In [8]:
# Creating array from list with type float
a = np.array([[1, 3, 4], [2, 9, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 3. 4.]
 [2. 9. 7.]]


In [9]:
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [10]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
			"Array type is complex:\n", d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [12]:
# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)


A random array:
 [[0.21717726 0.39982339]
 [0.39519071 0.45784583]]


In [13]:
# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [14]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                            "0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [15]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [16]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [17]:
#Arrange 'z' numbers between x and y
h = np.linspace(5,10,10)
h


array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [18]:
#even numbers between 0 to 10
i= np.linspace(0,10,6)
i

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [19]:
x = np.empty(2, dtype = int)
print("Matrix b : \n", x)
 
y = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", y)
 
z = np.empty([3, 3])
print("\nMatrix c : \n", z) #Return a new array of given shape and type, without initializing entries.

Matrix b : 
 [         0 1076101120]

Matrix a : 
 [[  199172010   -42154591]
 [-1846575826  1214862457]]

Matrix c : 
 [[0.55555556 1.11111111 1.66666667]
 [2.22222222 2.77777778 3.33333333]
 [3.88888889 4.44444444 5.        ]]


In [20]:
x1 = np.empty_like([2,2], dtype = int)
print("\nMatrix x1 : \n", x1)#Return a new array with the same shape and type as a given array


Matrix x1 : 
 [0 0]


In [21]:
##Return a 2-D array with ones on the diagonal and zeros elsewhere.
# 2x2 matrix with 1's on main diagonal
x3 = np.eye(2, dtype = float)
print("Matrix x3 : \n", x3)

# matrix with R=4 C=5 and 1 on diagonal
# below main diagonal
y3 = np.eye(4, 5, k = -1)
print("\nMatrix y3 : \n", y3)


Matrix x3 : 
 [[1. 0.]
 [0. 1.]]

Matrix y3 : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [22]:
#Return the identity array
# 2x2 matrix with 1's on main diagonal
x4 = np.identity(2, dtype = float)
print("Matrix x4 : \n", x4)


y4 = np.identity(4)
print("\nMatrix y4 : \n", y4)


Matrix x4 : 
 [[1. 0.]
 [0. 1.]]

Matrix y4 : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
#The numpy.ones() function returns a new array of given shape and type, with ones.

x5 = np.ones(2, dtype = int)
print("Matrix x5 : \n", x5)

y5 = np.ones([2, 2], dtype = int)
print("\nMatrix y5 : \n", y5)

z5 = np.ones([3, 3])
print("\nMatrix z5 : \n", z5)


Matrix x5 : 
 [1 1]

Matrix y5 : 
 [[1 1]
 [1 1]]

Matrix z5 : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
#The numpy.one_like() function returns an array of given shape and type as a given array, with ones

array1 = np.arange(10).reshape(5, 2)
print("Original array : \n", array1)


b7 = np.ones_like(array1, float)
print("\nMatrix b7 : \n", b7)

array1 = np.arange(8)
c7 = np.ones_like(array1)
print("\nMatrix c7 : \n", c7)


Original array : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Matrix b7 : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Matrix c7 : 
 [1 1 1 1 1 1 1 1]


In [25]:
a9 = [1, 2]
np.asarray(a9)
#Convert the input to an array.

array([1, 2])

In [40]:
#Convert the input to an ndarray, but pass ndarray subclasses through.
a10 = [1, 2]
np.asanyarray(a10)

array([1, 2])

In [41]:
#Return a contiguous array (ndim >= 1) in memory (C order).
x9 = np.arange(6).reshape(2,3)
np.ascontiguousarray(x9, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [42]:
#Return a contiguous flattened array.
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [43]:
#Move axes of an array to new positions.
x = np.zeros((3, 4, 5))
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [44]:
#Roll the specified axis backwards, until it lies in a given position.
a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [45]:
#Interchange two axes of an array.
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [47]:
#Reverse or permute the axes of an array; returns the modified array.
x = np.arange(4).reshape((2,2))
x


array([[0, 1],
       [2, 3]])

In [48]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [49]:
#Expand the shape of an array.
x = np.array([1, 2])
x.shape

(2,)

In [51]:
y = np.expand_dims(x, axis=0)
y.shape

(1, 2)

In [52]:
x = np.array([[1234]])
x.shape

(1, 1)

In [53]:
#Remove axes of length one from a.
np.squeeze(x)
# 0d array

array(1234)

In [54]:
# Interpret the input as a matrix.
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [55]:
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [56]:
# Return an array converted to a float type.
np.asfarray([2, 3])

array([2., 3.])

In [57]:
# Join a sequence of arrays along an existing axis.

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
# Join a sequence of arrays along a new axis.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
# Assemble an nd-array from nested lists of blocks.
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([
    [A,               np.zeros((2, 3))],
    [np.ones((3, 2)), B               ]
])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [62]:
# Stack arrays in sequence vertically (row wise).
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [63]:
# Stack arrays in sequence horizontally (column wise).
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
# Stack arrays in sequence depth wise (along third axis).
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [65]:
# Stack arrays in sequence vertically (row wise).
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [66]:
# Split an array into multiple sub-arrays as views into ary.
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [67]:
# Split array into multiple sub-arrays along the 3rd axis (depth).
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [68]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [69]:
# Split an array into multiple sub-arrays horizontally (column-wise).
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [70]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [73]:
# Split an array into multiple sub-arrays vertically (row-wise).
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [74]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [75]:
# Construct an array by repeating A the number of times given by reps.
a = np.array([0, 1, 2])
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [76]:
# Repeat elements of an array.
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [77]:
# Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [79]:
# Insert values along the given axis before the given indices.
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [80]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [81]:
# Append values to the end of an array.
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
# Find the unique elements of an array.
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

# Mathmatics Function

In [26]:
arr1 = np.array([[1, 3, 6],
                [4, 5, 2],
                [3, 8, 9]])

# maximum element of array
print ("Largest element is:", arr1.max())
print ("Row-wise maximum elements:",
                        arr.max(axis = 1))

# minimum element of array
print ("Column-wise minimum elements:",
                        arr1.min(axis = 0))

# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr1.cumsum(axis = 1))


Largest element is: 9
Row-wise maximum elements: [3 6]
Column-wise minimum elements: [1 3 2]
Cumulative sum along each row:
 [[ 1  4 10]
 [ 4  9 11]
 [ 3 11 20]]


In [27]:
np.sum([10,20]) #sum 

30

In [28]:
#using a variable that is sum of a+b
a1,b1 = 10,20
np.sum([a1,b1])

30

In [29]:
np.sum([[1,2],[5,6]],axis = 0)

array([6, 8])

In [30]:
np.sum([[1,2],[5,6]],axis = 1)

array([ 3, 11])

In [31]:
np.sum([[1,2],[5,6]])

14

In [32]:
np.subtract(10,20) #substraction

-10

In [33]:
np.multiply(2,3) #Multiplying two numbers

6

In [34]:
np.divide(10,5) #Dividing two numbers

2.0

In [35]:
a3 =np.array([2,4,6])

#exp,sqrt,sin,cos,log

print("Exponent : ",np.exp(a3))
print("Square root : ", np.sqrt(a3))
print("Sin : ", np.sin(a3))
print("Cos : ", np.cos(a3))
print("Log : ", np.log(a3))

Exponent :  [  7.3890561   54.59815003 403.42879349]
Square root :  [1.41421356 2.         2.44948974]
Sin :  [ 0.90929743 -0.7568025  -0.2794155 ]
Cos :  [-0.41614684 -0.65364362  0.96017029]
Log :  [0.69314718 1.38629436 1.79175947]


In [36]:
a3 =np.array([2,4,6])
b3 =np.array([1,2,3])
# matrix multiplication
print ("Matrix multiplication:\n", a3.dot(b3))

Matrix multiplication:
 28


In [37]:

a4 = np.array([[1, 2],
            [3, 4]])
b4 = np.array([[4, 3],
            [2, 1]])
print ("Matrix multiplication:\n", a4.dot(b4))

Matrix multiplication:
 [[ 8  5]
 [20 13]]


#  Sorting array: There is a simple np.sort method for sorting NumPy arrays

In [38]:
a5 = np.array([[1, 4, 2],
                [3, 4, 6],
                [0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n",
                    np.sort(a5, axis = None))

# sort array row-wise
print ("Row-wise sorted array:\n",
                np.sort(a5, axis = 1))

# specify sort algorithm
print ("Column wise sort by applying merge-sort:\n",
            np.sort(a5, axis = 0, kind = 'mergesort'))

# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
        ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

# Creating array
arr2 = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr2, order = 'name'))

print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr2, order = ['grad_year', 'cgpa']))


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
